/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface ReserveControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addReserves"
      | "coverageRatio"
      | "getReserveRatio"
      | "gold"
      | "goldPriceUsd6"
      | "manageReserve"
      | "navReserveUsd"
      | "owner"
      | "renounceOwnership"
      | "reserveCeilBps"
      | "reserveFloorBps"
      | "reserveRatio"
      | "reserves"
      | "setGoldPrice"
      | "setReserveRatio"
      | "setTreasury"
      | "totalReserves"
      | "transferOwnership"
      | "treasury"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "GoldPriceUpdated"
      | "OwnershipTransferred"
      | "ReserveDrained"
      | "ReserveFilled"
      | "ReserveRatioUpdated"
      | "ReservesAdded"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addReserves",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "coverageRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getReserveRatio",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "gold", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "goldPriceUsd6",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "manageReserve",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "navReserveUsd",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveCeilBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveFloorBps",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveRatio",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserves",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setGoldPrice",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setReserveRatio",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalReserves",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "addReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "coverageRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getReserveRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "gold", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "goldPriceUsd6",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "manageReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "navReserveUsd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveCeilBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveFloorBps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reserves", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setGoldPrice",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setReserveRatio",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
}

export namespace GoldPriceUpdatedEvent {
  export type InputTuple = [newPrice: BigNumberish];
  export type OutputTuple = [newPrice: bigint];
  export interface OutputObject {
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveDrainedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveFilledEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReserveRatioUpdatedEvent {
  export type InputTuple = [newRatio: BigNumberish];
  export type OutputTuple = [newRatio: bigint];
  export interface OutputObject {
    newRatio: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ReservesAddedEvent {
  export type InputTuple = [asset: AddressLike, amount: BigNumberish];
  export type OutputTuple = [asset: string, amount: bigint];
  export interface OutputObject {
    asset: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface ReserveController extends BaseContract {
  connect(runner?: ContractRunner | null): ReserveController;
  waitForDeployment(): Promise<this>;

  interface: ReserveControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addReserves: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  coverageRatio: TypedContractMethod<[], [bigint], "view">;

  getReserveRatio: TypedContractMethod<[], [bigint], "view">;

  gold: TypedContractMethod<[], [string], "view">;

  goldPriceUsd6: TypedContractMethod<[], [bigint], "view">;

  manageReserve: TypedContractMethod<
    [currentRatio: BigNumberish],
    [void],
    "nonpayable"
  >;

  navReserveUsd: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  reserveCeilBps: TypedContractMethod<[], [bigint], "view">;

  reserveFloorBps: TypedContractMethod<[], [bigint], "view">;

  reserveRatio: TypedContractMethod<[], [bigint], "view">;

  reserves: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  setGoldPrice: TypedContractMethod<
    [newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  setReserveRatio: TypedContractMethod<
    [newRatio: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  totalReserves: TypedContractMethod<[asset: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addReserves"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "coverageRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getReserveRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "gold"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "goldPriceUsd6"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "manageReserve"
  ): TypedContractMethod<[currentRatio: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "navReserveUsd"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "reserveCeilBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserveFloorBps"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserveRatio"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserves"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "setGoldPrice"
  ): TypedContractMethod<[newPrice: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setReserveRatio"
  ): TypedContractMethod<[newRatio: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "totalReserves"
  ): TypedContractMethod<[asset: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "GoldPriceUpdated"
  ): TypedContractEvent<
    GoldPriceUpdatedEvent.InputTuple,
    GoldPriceUpdatedEvent.OutputTuple,
    GoldPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "ReserveDrained"
  ): TypedContractEvent<
    ReserveDrainedEvent.InputTuple,
    ReserveDrainedEvent.OutputTuple,
    ReserveDrainedEvent.OutputObject
  >;
  getEvent(
    key: "ReserveFilled"
  ): TypedContractEvent<
    ReserveFilledEvent.InputTuple,
    ReserveFilledEvent.OutputTuple,
    ReserveFilledEvent.OutputObject
  >;
  getEvent(
    key: "ReserveRatioUpdated"
  ): TypedContractEvent<
    ReserveRatioUpdatedEvent.InputTuple,
    ReserveRatioUpdatedEvent.OutputTuple,
    ReserveRatioUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "ReservesAdded"
  ): TypedContractEvent<
    ReservesAddedEvent.InputTuple,
    ReservesAddedEvent.OutputTuple,
    ReservesAddedEvent.OutputObject
  >;

  filters: {
    "GoldPriceUpdated(uint256)": TypedContractEvent<
      GoldPriceUpdatedEvent.InputTuple,
      GoldPriceUpdatedEvent.OutputTuple,
      GoldPriceUpdatedEvent.OutputObject
    >;
    GoldPriceUpdated: TypedContractEvent<
      GoldPriceUpdatedEvent.InputTuple,
      GoldPriceUpdatedEvent.OutputTuple,
      GoldPriceUpdatedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "ReserveDrained(uint256)": TypedContractEvent<
      ReserveDrainedEvent.InputTuple,
      ReserveDrainedEvent.OutputTuple,
      ReserveDrainedEvent.OutputObject
    >;
    ReserveDrained: TypedContractEvent<
      ReserveDrainedEvent.InputTuple,
      ReserveDrainedEvent.OutputTuple,
      ReserveDrainedEvent.OutputObject
    >;

    "ReserveFilled(uint256)": TypedContractEvent<
      ReserveFilledEvent.InputTuple,
      ReserveFilledEvent.OutputTuple,
      ReserveFilledEvent.OutputObject
    >;
    ReserveFilled: TypedContractEvent<
      ReserveFilledEvent.InputTuple,
      ReserveFilledEvent.OutputTuple,
      ReserveFilledEvent.OutputObject
    >;

    "ReserveRatioUpdated(uint256)": TypedContractEvent<
      ReserveRatioUpdatedEvent.InputTuple,
      ReserveRatioUpdatedEvent.OutputTuple,
      ReserveRatioUpdatedEvent.OutputObject
    >;
    ReserveRatioUpdated: TypedContractEvent<
      ReserveRatioUpdatedEvent.InputTuple,
      ReserveRatioUpdatedEvent.OutputTuple,
      ReserveRatioUpdatedEvent.OutputObject
    >;

    "ReservesAdded(address,uint256)": TypedContractEvent<
      ReservesAddedEvent.InputTuple,
      ReservesAddedEvent.OutputTuple,
      ReservesAddedEvent.OutputObject
    >;
    ReservesAdded: TypedContractEvent<
      ReservesAddedEvent.InputTuple,
      ReservesAddedEvent.OutputTuple,
      ReservesAddedEvent.OutputObject
    >;
  };
}
