/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITreasuryPay,
  ITreasuryPayInterface,
} from "../../../contracts/Vault.sol/ITreasuryPay";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "usd6",
        type: "uint256",
      },
    ],
    name: "payOut",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class ITreasuryPay__factory {
  static readonly abi = _abi;
  static createInterface(): ITreasuryPayInterface {
    return new Interface(_abi) as ITreasuryPayInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ITreasuryPay {
    return new Contract(address, _abi, runner) as unknown as ITreasuryPay;
  }
}
