/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface InvestmentEscrowInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "closeInvestment"
      | "investments"
      | "nextInvestmentId"
      | "openInvestment"
      | "treasury"
      | "usdc"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "InvestmentClosed" | "InvestmentOpened"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "closeInvestment",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "investments",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "nextInvestmentId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "openInvestment",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "closeInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investments",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextInvestmentId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "openInvestment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export namespace InvestmentClosedEvent {
  export type InputTuple = [
    investmentId: BigNumberish,
    returnedAmount: BigNumberish,
    profit: BigNumberish
  ];
  export type OutputTuple = [
    investmentId: bigint,
    returnedAmount: bigint,
    profit: bigint
  ];
  export interface OutputObject {
    investmentId: bigint;
    returnedAmount: bigint;
    profit: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentOpenedEvent {
  export type InputTuple = [
    investmentId: BigNumberish,
    vendor: AddressLike,
    amountUsd6: BigNumberish,
    duration: BigNumberish
  ];
  export type OutputTuple = [
    investmentId: bigint,
    vendor: string,
    amountUsd6: bigint,
    duration: bigint
  ];
  export interface OutputObject {
    investmentId: bigint;
    vendor: string;
    amountUsd6: bigint;
    duration: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface InvestmentEscrow extends BaseContract {
  connect(runner?: ContractRunner | null): InvestmentEscrow;
  waitForDeployment(): Promise<this>;

  interface: InvestmentEscrowInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  closeInvestment: TypedContractMethod<
    [investmentId: BigNumberish, returnedAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  investments: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        vendor: string;
        amountUsd6: bigint;
        startTime: bigint;
        endTime: bigint;
        returned: boolean;
      }
    ],
    "view"
  >;

  nextInvestmentId: TypedContractMethod<[], [bigint], "view">;

  openInvestment: TypedContractMethod<
    [vendor: AddressLike, amountUsd6: BigNumberish, duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "closeInvestment"
  ): TypedContractMethod<
    [investmentId: BigNumberish, returnedAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "investments"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, bigint, bigint, bigint, boolean] & {
        vendor: string;
        amountUsd6: bigint;
        startTime: bigint;
        endTime: bigint;
        returned: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "nextInvestmentId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "openInvestment"
  ): TypedContractMethod<
    [vendor: AddressLike, amountUsd6: BigNumberish, duration: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "InvestmentClosed"
  ): TypedContractEvent<
    InvestmentClosedEvent.InputTuple,
    InvestmentClosedEvent.OutputTuple,
    InvestmentClosedEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentOpened"
  ): TypedContractEvent<
    InvestmentOpenedEvent.InputTuple,
    InvestmentOpenedEvent.OutputTuple,
    InvestmentOpenedEvent.OutputObject
  >;

  filters: {
    "InvestmentClosed(uint256,uint256,uint256)": TypedContractEvent<
      InvestmentClosedEvent.InputTuple,
      InvestmentClosedEvent.OutputTuple,
      InvestmentClosedEvent.OutputObject
    >;
    InvestmentClosed: TypedContractEvent<
      InvestmentClosedEvent.InputTuple,
      InvestmentClosedEvent.OutputTuple,
      InvestmentClosedEvent.OutputObject
    >;

    "InvestmentOpened(uint256,address,uint256,uint256)": TypedContractEvent<
      InvestmentOpenedEvent.InputTuple,
      InvestmentOpenedEvent.OutputTuple,
      InvestmentOpenedEvent.OutputObject
    >;
    InvestmentOpened: TypedContractEvent<
      InvestmentOpenedEvent.InputTuple,
      InvestmentOpenedEvent.OutputTuple,
      InvestmentOpenedEvent.OutputObject
    >;
  };
}
