/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  MockAmmPair,
  MockAmmPairInterface,
} from "../../contracts/MockAmmPair";

const _abi = [
  {
    inputs: [],
    name: "SWAP_FEE_BPS",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "reserveIn",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "reserveOut",
        type: "uint256",
      },
    ],
    name: "swap",
    outputs: [
      {
        internalType: "uint256",
        name: "amountOut",
        type: "uint256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b506101e3806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c806367a6c4401461003b5780639d9892cd14610055575b600080fd5b610043601e81565b60405190815260200160405180910390f35b610043610063366004610106565b600080831180156100745750600082115b6100b75760405162461bcd60e51b815260206004820152601060248201526f496e76616c696420726573657276657360801b604482015260640160405180910390fd5b60006100c6601e612710610148565b6100d09086610161565b9050806100df85612710610161565b6100e99190610178565b6100f38483610161565b6100fd919061018b565b95945050505050565b60008060006060848603121561011b57600080fd5b505081359360208301359350604090920135919050565b634e487b7160e01b600052601160045260246000fd5b8181038181111561015b5761015b610132565b92915050565b808202811582820484141761015b5761015b610132565b8082018082111561015b5761015b610132565b6000826101a857634e487b7160e01b600052601260045260246000fd5b50049056fea264697066735822122032e98c69132924c707ed1c3ebb3e3f162306f5326d6faf054d1121eddd18d3a464736f6c63430008180033";

type MockAmmPairConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: MockAmmPairConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class MockAmmPair__factory extends ContractFactory {
  constructor(...args: MockAmmPairConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      MockAmmPair & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): MockAmmPair__factory {
    return super.connect(runner) as MockAmmPair__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MockAmmPairInterface {
    return new Interface(_abi) as MockAmmPairInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): MockAmmPair {
    return new Contract(address, _abi, runner) as unknown as MockAmmPair;
  }
}
