/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ITreasury,
  ITreasuryInterface,
} from "../../../contracts/interfaces/ITreasury";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "amountUsd6",
        type: "uint256",
      },
    ],
    name: "canAdmit",
    outputs: [
      {
        internalType: "bool",
        name: "",
        type: "bool",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class ITreasury__factory {
  static readonly abi = _abi;
  static createInterface(): ITreasuryInterface {
    return new Interface(_abi) as ITreasuryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ITreasury {
    return new Contract(address, _abi, runner) as unknown as ITreasury;
  }
}
