const fs = require('fs');
const path = require('path');

async function main() {
  // Read deployment addresses from deployments.json or hardhat artifacts
  const deploymentsPath = path.join(__dirname, '../deployments.json');
  
  if (!fs.existsSync(deploymentsPath)) {
    console.error('No deployments.json found. Run deployment first.');
    process.exit(1);
  }
  
  const deployments = JSON.parse(fs.readFileSync(deploymentsPath, 'utf8'));
  
  const content = `// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by scripts/generateAddresses.js
export const CONTRACT_ADDRESSES = ${JSON.stringify(deployments, null, 2)};

export const contractAddresses = {
  sagToken: CONTRACT_ADDRESSES.SAGToken,
  mockUSDC: CONTRACT_ADDRESSES.MockUSDC,
  vault: CONTRACT_ADDRESSES.Vault,
  treasury: CONTRACT_ADDRESSES.Treasury,
  reserveController: CONTRACT_ADDRESSES.ReserveController,
};
`;
  
  const outputPath = path.join(__dirname, '../frontend/src/lib/addresses.ts');
  fs.writeFileSync(outputPath, content);
  console.log('Generated addresses.ts successfully!');
}

main().catch(console.error);
