/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export declare namespace Vault {
  export type DepositReceiptStruct = {
    user: AddressLike;
    asset: AddressLike;
    amount: BigNumberish;
    amountUsd6: BigNumberish;
    shares: BigNumberish;
    createdAt: BigNumberish;
    lockUntil: BigNumberish;
    withdrawn: boolean;
  };

  export type DepositReceiptStructOutput = [
    user: string,
    asset: string,
    amount: bigint,
    amountUsd6: bigint,
    shares: bigint,
    createdAt: bigint,
    lockUntil: bigint,
    withdrawn: boolean
  ] & {
    user: string;
    asset: string;
    amount: bigint;
    amountUsd6: bigint;
    shares: bigint;
    createdAt: bigint;
    lockUntil: bigint;
    withdrawn: boolean;
  };

  export type CreditStruct = {
    amountUsd6: BigNumberish;
    unlockAt: BigNumberish;
    claimed: boolean;
  };

  export type CreditStructOutput = [
    amountUsd6: bigint,
    unlockAt: bigint,
    claimed: boolean
  ] & { amountUsd6: bigint; unlockAt: bigint; claimed: boolean };
}

export interface VaultInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "assets"
      | "balanceOf(address)"
      | "balanceOf(address,address)"
      | "claimCredit"
      | "creditCount"
      | "credits"
      | "deposit"
      | "depositInfo"
      | "depositedUsd"
      | "deposits"
      | "getUserCredits"
      | "issueCredit"
      | "lockDuration"
      | "nextDepositId"
      | "owner"
      | "pause"
      | "paused"
      | "pendingCreditsUsd6"
      | "principalOf"
      | "receiptCount"
      | "receipts"
      | "renounceOwnership"
      | "setAsset"
      | "setLockDuration"
      | "setTreasury"
      | "sharesOf"
      | "sweep"
      | "totalPrincipalByAsset"
      | "totalSharesByAsset"
      | "totals"
      | "transferOwnership"
      | "treasury"
      | "unpause"
      | "userDeposits"
      | "userDepositsOf"
      | "withdrawPrincipal"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AssetSet"
      | "DepositAccepted"
      | "LockSecondsSet"
      | "OwnershipTransferred"
      | "Paused"
      | "PrincipalWithdrawn"
      | "ProfitCreditClaimed"
      | "ProfitCreditIssued"
      | "TreasurySet"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(functionFragment: "assets", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "balanceOf(address)",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf(address,address)",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "claimCredit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "creditCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "credits",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deposit",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositedUsd",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deposits",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getUserCredits",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCredit",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "lockDuration",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "nextDepositId",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingCreditsUsd6",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "principalOf",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receiptCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "receipts",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setAsset",
    values: [AddressLike, boolean, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setLockDuration",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setTreasury",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sharesOf",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "sweep",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalPrincipalByAsset",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalSharesByAsset",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "totals", values: [AddressLike]): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "treasury", values?: undefined): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "userDeposits",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "userDepositsOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawPrincipal",
    values: [BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "assets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "balanceOf(address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "balanceOf(address,address)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "creditCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "credits", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "deposit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "depositInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositedUsd",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deposits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getUserCredits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCredit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "lockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "nextDepositId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingCreditsUsd6",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "principalOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "receiptCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "receipts", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setAsset", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setLockDuration",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTreasury",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "sharesOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sweep", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalPrincipalByAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSharesByAsset",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "totals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "treasury", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "userDeposits",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "userDepositsOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawPrincipal",
    data: BytesLike
  ): Result;
}

export namespace AssetSetEvent {
  export type InputTuple = [
    asset: AddressLike,
    enabled: boolean,
    decimals: BigNumberish,
    oracle: AddressLike
  ];
  export type OutputTuple = [
    asset: string,
    enabled: boolean,
    decimals: bigint,
    oracle: string
  ];
  export interface OutputObject {
    asset: string;
    enabled: boolean;
    decimals: bigint;
    oracle: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DepositAcceptedEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    asset: AddressLike,
    amount: BigNumberish,
    usd6: BigNumberish,
    shares: BigNumberish,
    lockUntil: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    asset: string,
    amount: bigint,
    usd6: bigint,
    shares: bigint,
    lockUntil: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    asset: string;
    amount: bigint;
    usd6: bigint;
    shares: bigint;
    lockUntil: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LockSecondsSetEvent {
  export type InputTuple = [seconds_: BigNumberish];
  export type OutputTuple = [seconds_: bigint];
  export interface OutputObject {
    seconds_: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PrincipalWithdrawnEvent {
  export type InputTuple = [
    id: BigNumberish,
    user: AddressLike,
    asset: AddressLike,
    amount: BigNumberish
  ];
  export type OutputTuple = [
    id: bigint,
    user: string,
    asset: string,
    amount: bigint
  ];
  export interface OutputObject {
    id: bigint;
    user: string;
    asset: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfitCreditClaimedEvent {
  export type InputTuple = [user: AddressLike, amountUsd6: BigNumberish];
  export type OutputTuple = [user: string, amountUsd6: bigint];
  export interface OutputObject {
    user: string;
    amountUsd6: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProfitCreditIssuedEvent {
  export type InputTuple = [
    user: AddressLike,
    amountUsd6: BigNumberish,
    unlockAt: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    amountUsd6: bigint,
    unlockAt: bigint
  ];
  export interface OutputObject {
    user: string;
    amountUsd6: bigint;
    unlockAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TreasurySetEvent {
  export type InputTuple = [treasury: AddressLike];
  export type OutputTuple = [treasury: string];
  export interface OutputObject {
    treasury: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface Vault extends BaseContract {
  connect(runner?: ContractRunner | null): Vault;
  waitForDeployment(): Promise<this>;

  interface: VaultInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  assets: TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, string] & {
        enabled: boolean;
        decimals: bigint;
        oracle: string;
      }
    ],
    "view"
  >;

  "balanceOf(address)": TypedContractMethod<
    [user: AddressLike],
    [bigint],
    "view"
  >;

  "balanceOf(address,address)": TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [bigint],
    "view"
  >;

  claimCredit: TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;

  creditCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  credits: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        amountUsd6: bigint;
        unlockAt: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;

  deposit: TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositInfo: TypedContractMethod<
    [id: BigNumberish],
    [Vault.DepositReceiptStructOutput],
    "view"
  >;

  depositedUsd: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  deposits: TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        user: string;
        asset: string;
        amount: bigint;
        amountUsd6: bigint;
        shares: bigint;
        createdAt: bigint;
        lockUntil: bigint;
        withdrawn: boolean;
      }
    ],
    "view"
  >;

  getUserCredits: TypedContractMethod<
    [user: AddressLike],
    [Vault.CreditStructOutput[]],
    "view"
  >;

  issueCredit: TypedContractMethod<
    [user: AddressLike, amountUsd6: BigNumberish, unlockAt: BigNumberish],
    [void],
    "nonpayable"
  >;

  lockDuration: TypedContractMethod<[], [bigint], "view">;

  nextDepositId: TypedContractMethod<[], [bigint], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  pendingCreditsUsd6: TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { total: bigint; unlocked: bigint }],
    "view"
  >;

  principalOf: TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [bigint],
    "view"
  >;

  receiptCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  receipts: TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [Vault.DepositReceiptStructOutput],
    "view"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setAsset: TypedContractMethod<
    [
      asset: AddressLike,
      enabled: boolean,
      decimals: BigNumberish,
      oracle: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  setLockDuration: TypedContractMethod<
    [_duration: BigNumberish],
    [void],
    "nonpayable"
  >;

  setTreasury: TypedContractMethod<
    [_treasury: AddressLike],
    [void],
    "nonpayable"
  >;

  sharesOf: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;

  sweep: TypedContractMethod<
    [token: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;

  totalPrincipalByAsset: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  totalSharesByAsset: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  totals: TypedContractMethod<
    [asset: AddressLike],
    [[bigint, bigint] & { principal: bigint; shares: bigint }],
    "view"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  treasury: TypedContractMethod<[], [string], "view">;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  userDeposits: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  userDepositsOf: TypedContractMethod<[user: AddressLike], [bigint[]], "view">;

  withdrawPrincipal: TypedContractMethod<
    [id: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "assets"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [boolean, bigint, string] & {
        enabled: boolean;
        decimals: bigint;
        oracle: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "balanceOf(address)"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "balanceOf(address,address)"
  ): TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "claimCredit"
  ): TypedContractMethod<[index: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "creditCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "credits"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, bigint, boolean] & {
        amountUsd6: bigint;
        unlockAt: bigint;
        claimed: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "deposit"
  ): TypedContractMethod<
    [asset: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositInfo"
  ): TypedContractMethod<
    [id: BigNumberish],
    [Vault.DepositReceiptStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "depositedUsd"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "deposits"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [
      [string, string, bigint, bigint, bigint, bigint, bigint, boolean] & {
        user: string;
        asset: string;
        amount: bigint;
        amountUsd6: bigint;
        shares: bigint;
        createdAt: bigint;
        lockUntil: bigint;
        withdrawn: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getUserCredits"
  ): TypedContractMethod<
    [user: AddressLike],
    [Vault.CreditStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueCredit"
  ): TypedContractMethod<
    [user: AddressLike, amountUsd6: BigNumberish, unlockAt: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "lockDuration"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "nextDepositId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "pendingCreditsUsd6"
  ): TypedContractMethod<
    [user: AddressLike],
    [[bigint, bigint] & { total: bigint; unlocked: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "principalOf"
  ): TypedContractMethod<
    [user: AddressLike, asset: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "receiptCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "receipts"
  ): TypedContractMethod<
    [user: AddressLike, index: BigNumberish],
    [Vault.DepositReceiptStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setAsset"
  ): TypedContractMethod<
    [
      asset: AddressLike,
      enabled: boolean,
      decimals: BigNumberish,
      oracle: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setLockDuration"
  ): TypedContractMethod<[_duration: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setTreasury"
  ): TypedContractMethod<[_treasury: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "sharesOf"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "sweep"
  ): TypedContractMethod<
    [token: AddressLike, to: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalPrincipalByAsset"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSharesByAsset"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "totals"
  ): TypedContractMethod<
    [asset: AddressLike],
    [[bigint, bigint] & { principal: bigint; shares: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "treasury"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "userDeposits"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "userDepositsOf"
  ): TypedContractMethod<[user: AddressLike], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "withdrawPrincipal"
  ): TypedContractMethod<
    [id: BigNumberish, to: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AssetSet"
  ): TypedContractEvent<
    AssetSetEvent.InputTuple,
    AssetSetEvent.OutputTuple,
    AssetSetEvent.OutputObject
  >;
  getEvent(
    key: "DepositAccepted"
  ): TypedContractEvent<
    DepositAcceptedEvent.InputTuple,
    DepositAcceptedEvent.OutputTuple,
    DepositAcceptedEvent.OutputObject
  >;
  getEvent(
    key: "LockSecondsSet"
  ): TypedContractEvent<
    LockSecondsSetEvent.InputTuple,
    LockSecondsSetEvent.OutputTuple,
    LockSecondsSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PrincipalWithdrawn"
  ): TypedContractEvent<
    PrincipalWithdrawnEvent.InputTuple,
    PrincipalWithdrawnEvent.OutputTuple,
    PrincipalWithdrawnEvent.OutputObject
  >;
  getEvent(
    key: "ProfitCreditClaimed"
  ): TypedContractEvent<
    ProfitCreditClaimedEvent.InputTuple,
    ProfitCreditClaimedEvent.OutputTuple,
    ProfitCreditClaimedEvent.OutputObject
  >;
  getEvent(
    key: "ProfitCreditIssued"
  ): TypedContractEvent<
    ProfitCreditIssuedEvent.InputTuple,
    ProfitCreditIssuedEvent.OutputTuple,
    ProfitCreditIssuedEvent.OutputObject
  >;
  getEvent(
    key: "TreasurySet"
  ): TypedContractEvent<
    TreasurySetEvent.InputTuple,
    TreasurySetEvent.OutputTuple,
    TreasurySetEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "AssetSet(address,bool,uint8,address)": TypedContractEvent<
      AssetSetEvent.InputTuple,
      AssetSetEvent.OutputTuple,
      AssetSetEvent.OutputObject
    >;
    AssetSet: TypedContractEvent<
      AssetSetEvent.InputTuple,
      AssetSetEvent.OutputTuple,
      AssetSetEvent.OutputObject
    >;

    "DepositAccepted(uint256,address,address,uint256,uint256,uint256,uint64)": TypedContractEvent<
      DepositAcceptedEvent.InputTuple,
      DepositAcceptedEvent.OutputTuple,
      DepositAcceptedEvent.OutputObject
    >;
    DepositAccepted: TypedContractEvent<
      DepositAcceptedEvent.InputTuple,
      DepositAcceptedEvent.OutputTuple,
      DepositAcceptedEvent.OutputObject
    >;

    "LockSecondsSet(uint64)": TypedContractEvent<
      LockSecondsSetEvent.InputTuple,
      LockSecondsSetEvent.OutputTuple,
      LockSecondsSetEvent.OutputObject
    >;
    LockSecondsSet: TypedContractEvent<
      LockSecondsSetEvent.InputTuple,
      LockSecondsSetEvent.OutputTuple,
      LockSecondsSetEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PrincipalWithdrawn(uint256,address,address,uint256)": TypedContractEvent<
      PrincipalWithdrawnEvent.InputTuple,
      PrincipalWithdrawnEvent.OutputTuple,
      PrincipalWithdrawnEvent.OutputObject
    >;
    PrincipalWithdrawn: TypedContractEvent<
      PrincipalWithdrawnEvent.InputTuple,
      PrincipalWithdrawnEvent.OutputTuple,
      PrincipalWithdrawnEvent.OutputObject
    >;

    "ProfitCreditClaimed(address,uint256)": TypedContractEvent<
      ProfitCreditClaimedEvent.InputTuple,
      ProfitCreditClaimedEvent.OutputTuple,
      ProfitCreditClaimedEvent.OutputObject
    >;
    ProfitCreditClaimed: TypedContractEvent<
      ProfitCreditClaimedEvent.InputTuple,
      ProfitCreditClaimedEvent.OutputTuple,
      ProfitCreditClaimedEvent.OutputObject
    >;

    "ProfitCreditIssued(address,uint256,uint64)": TypedContractEvent<
      ProfitCreditIssuedEvent.InputTuple,
      ProfitCreditIssuedEvent.OutputTuple,
      ProfitCreditIssuedEvent.OutputObject
    >;
    ProfitCreditIssued: TypedContractEvent<
      ProfitCreditIssuedEvent.InputTuple,
      ProfitCreditIssuedEvent.OutputTuple,
      ProfitCreditIssuedEvent.OutputObject
    >;

    "TreasurySet(address)": TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;
    TreasurySet: TypedContractEvent<
      TreasurySetEvent.InputTuple,
      TreasurySetEvent.OutputTuple,
      TreasurySetEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
