/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface TreasuryPayMockInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admit"
      | "canAdmit"
      | "payOut"
      | "payOutUsd6"
      | "setAdmit"
      | "usdc"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "admit", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "canAdmit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "payOut",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "payOutUsd6",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "setAdmit", values: [boolean]): string;
  encodeFunctionData(functionFragment: "usdc", values?: undefined): string;

  decodeFunctionResult(functionFragment: "admit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "canAdmit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payOut", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "payOutUsd6", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "setAdmit", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "usdc", data: BytesLike): Result;
}

export interface TreasuryPayMock extends BaseContract {
  connect(runner?: ContractRunner | null): TreasuryPayMock;
  waitForDeployment(): Promise<this>;

  interface: TreasuryPayMockInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admit: TypedContractMethod<[], [boolean], "view">;

  canAdmit: TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;

  payOut: TypedContractMethod<
    [to: AddressLike, usd6: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  payOutUsd6: TypedContractMethod<
    [to: AddressLike, usd6: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  setAdmit: TypedContractMethod<[v: boolean], [void], "nonpayable">;

  usdc: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admit"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "canAdmit"
  ): TypedContractMethod<[arg0: BigNumberish], [boolean], "view">;
  getFunction(
    nameOrSignature: "payOut"
  ): TypedContractMethod<
    [to: AddressLike, usd6: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "payOutUsd6"
  ): TypedContractMethod<
    [to: AddressLike, usd6: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAdmit"
  ): TypedContractMethod<[v: boolean], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "usdc"
  ): TypedContractMethod<[], [string], "view">;

  filters: {};
}
